### PR TITLE
Expose http and hotrod as ClusterIp services #19

### PR DESCRIPTION
**Pull request by galderz**
My first PR 🙈

### CODE REVIEW

**Comment by galderz** [comment]
Abandoning the idea of Hot Rod testing for the service. Client is limited in functionality and I've not figured out the steps to make it accessible externally when unencrypted. So instead I'll just rely on the HTTP port service, which we can easily test and we know how to expose externally. I'll remove the Hot Rod testing commit.

**Comment by galderz** [comment]
@rigazilla This is ready to be integrated in CI agrees. Added HTTP testing of the service exposed via a route.

**Comment by galderz** [comment]
And CI agrees :)

**Comment by rigazilla** [comment]
merged, thanks!

**Pull request merged**
