### PR TITLE
ISPN-9875 Code relocation from https://github.com/rigazilla/infinispa…

### PR DESCRIPTION
**Pull request by gustavonalle**
…n-operator

https://issues.jboss.org/browse/ISPN-9875

### CODE REVIEW

**Comment by rigazilla** [comment]
I've tried the readme: I'm having a problem in running the operator locally.
However the operator deployed works so my idea is to merge this and create a jira for the local run.
Ok for you @gustavonalle ?

**Comment by gustavonalle** [comment]
What's the issue of running it locally?

**Comment by gustavonalle** [comment]
Btw, we're not using JIRA anymore for the operator, but https://github.com/jboss-dockerfiles/infinispan-server-operator/issues  ;)

**Comment by rigazilla** [comment]
When I deploy the infinispan cluster yaml, the nodes stuck in ContainerCreating.
This with oc cluster up 3.11

**Comment by rigazilla** [comment]
> Btw, we're not using JIRA anymore for the operator, but https://github.com/jboss-dockerfiles/infinispan-server-operator/issues ;)

Uh is this ok with all the sprint, scrum, mgmt stuff?

**Comment by rigazilla** [comment]
I have this error (I'll investigate later):
```
INFO[0000] Running the operator locally.                
{"level":"info","ts":1548691759.995863,"logger":"cmd","msg":"Go Version: go1.11.4"}
{"level":"info","ts":1548691759.9959056,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1548691759.9959118,"logger":"cmd","msg":"Version of operator-sdk: v0.4.0"}
{"level":"info","ts":1548691759.9985077,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1548691759.9985504,"logger":"leader","msg":"Skipping leader election; not running in a cluster."}
{"level":"info","ts":1548691760.045287,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1548691760.0454493,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"infinispan-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1548691760.0455527,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"infinispan-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1548691760.045618,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1548691760.1458318,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"infinispan-controller"}
{"level":"info","ts":1548691760.2461884,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"infinispan-controller","worker count":1}
{"level":"info","ts":1548691818.0628116,"logger":"controller_infinispan","msg":"Reconciling Infinispan","Request.Namespace":"myproject","Request.Name":"example-infinispan"}
{"level":"info","ts":1548691818.062861,"logger":"controller_infinispan","msg":"Creating a new Deployment","Request.Namespace":"myproject","Request.Name":"example-infinispan","Deployment.Namespace":"myproject","Deployment.Name":"example-infinispan"}
{"level":"info","ts":1548691818.0755312,"logger":"controller_infinispan","msg":"Reconciling Infinispan","Request.Namespace":"myproject","Request.Name":"example-infinispan"}
{"level":"error","ts":1548691818.0877678,"logger":"controller_infinispan","msg":"failed to update Deployment","Request.Namespace":"myproject","Request.Name":"example-infinispan","Deployment.Namespace":"myproject","Deployment.Name":"example-infinispan","error":"Operation cannot be fulfilled on deployments.apps \"example-infinispan\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/jboss-dockerfiles/infinispan-server-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/jboss-dockerfiles/infinispan-server-operator/pkg/controller/infinispan.(*ReconcileInfinispan).Reconcile\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/pkg/controller/infinispan/infinispan_controller.go:133\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"error","ts":1548691818.0878704,"logger":"kubebuilder.controller","msg":"Reconciler error","controller":"infinispan-controller","request":"myproject/example-infinispan","error":"Operation cannot be fulfilled on deployments.apps \"example-infinispan\": the object has been modified; please apply your changes to the latest version and try again","stacktrace":"github.com/jboss-dockerfiles/infinispan-server-operator/vendor/github.com/go-logr/zapr.(*zapLogger).Error\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/github.com/go-logr/zapr/zapr.go:128\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:215\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134\ngithub.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until\n\t/home/rigazilla/go/src/github.com/jboss-dockerfiles/infinispan-server-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88"}
{"level":"info","ts":1548691819.088052,"logger":"controller_infinispan","msg":"Reconciling Infinispan","Request.Namespace":"myproject","Request.Name":"example-infinispan"}
{"level":"info","ts":1548691819.0910387,"logger":"controller_infinispan","msg":"Reconciling Infinispan","Request.Namespace":"myproject","Request.Name":"example-infinispan"}
{"level":"info","ts":1548691819.199012,"logger":"controller_infinispan","msg":"Reconciling Infinispan","Request.Namespace":"myproject","Request.Name":"example-infinispan"}
{"level":"info","ts":1548691819.2096207,"logger":"controller_infinispan","msg":"Reconciling Infinispan","Request.Namespace":"myproject","Request.Name":"example-infinispan"}
{"level":"info","ts":1548691819.2164865,"logger":"controller_infinispan","msg":"Reconciling Infinispan","Request.Namespace":"myproject","
```

**Comment by gustavonalle** [comment]
Those errors are "normal", there's a race inside the controller where sometimes the CRD is not fully installed when the operator is started, but it should create the containers eventually. Does the operator crash?

So let's integrate this issue as you proposed, and please open a separate issue with more detailed logs

**Comment by rigazilla** [comment]
the operator doesn't creash, it loops trying to create the pods

**Comment by rigazilla** [comment]
thank you, merged

**Pull request merged**
